$include:
  - ./conf/base.yml

fine_tune: True
fine_tune_checkpoint: ./runs/11-08-mid/latest/vampnet/weights.pth

save_path: ./runs/bowl-11-08-mid

VampNet.max_seq_len: 512
NoamScheduler.warmup: 500

batch_size: 28
num_workers: 18
save_iters: [500, 1000, 5000, 10000, 20000, 30000, 40000, 50000, 100000]
sample_freq: 5000
val_freq: 1000

AdamW.lr: 0.0001
VampNet.max_seq_len: 512

num_iters: 500000

DACDataset.metadata_csvs:
  - ./data/metadata/salad_bowl.csv

