
codec_ckpt: ./models/vampnet/codec.pth
save_path: ckpt

num_iters: 1000002
save_iters: [100000, 200000, 400000, 600000, 1000000]
val_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, ]
sample_freq: 10000
val_freq: 1000

batch_size: 36
val_batch_size: 36
num_workers: 16

# Optimization
amp: false

AdamW.lr: 0.001

NoamScheduler.factor: 2.0
NoamScheduler.warmup: 3000

VampNet.vocab_size: 1024
VampNet.n_codebooks: 9
VampNet.n_conditioning_codebooks: 0
VampNet.embedding_dim: 1024
VampNet.n_layers: 12
VampNet.n_heads: 12
VampNet.dropout: 0.05
VampNet.max_seq_len: 512

DACDataset.metadata_csvs: 
- ./data/metadata/prosound_redacted.csv
- ./data/metadata/fma_full.csv
- ./data/metadata/disco-1m.csv

DACDataset.seq_len: 512 
train/DACDataset.split: "train"
val/DACDataset.split: "val"
val/DACDataset.length: 2000
test/DACDataset.split: "test"
test/DACDataset.length: 2000