$include:
  - conf/base.yml

fine_tune: True

train/AudioDataset.n_examples: 100000000
val/AudioDataset.n_examples: 500


NoamScheduler.warmup: 500

batch_size: 7
num_workers: 7
save_iters: [10000, 20000, 30000, 40000, 50000]
sample_freq: 1000
val_freq: 500

AdamW.lr: 0.0001

num_iters: 500000
