$include:
  - conf/base.yml

batch_size: 64
val_batch_size: 64
num_workers: 18

train/AudioDataset.n_examples: 10000000
train/AudioLoader.sources:
  - data/prosound_core_complete/train

val/AudioDataset.n_examples: 10000
val/AudioLoader.sources:
  - data/prosound_core_complete/val